import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'hi' | 'mr';

const translations = {
  en: {
    brand: 'VeriLabel', motto: 'Every Label, Verified.', prototype: 'Prototype', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark',
    roleTitle: 'Are you an Officer or a Customer?', roleSubtitle: 'Choose how you want to use VeriLabel.', officer: 'Officer', customer: 'Customer', officerDesc: 'Inspect products, review compliance, evidence, and reports.', customerDesc: 'Verify a packaged product label in a guided flow.', continue: 'Continue',
    login: 'Officer Login', loginSub: 'Access the prototype enforcement workspace.', officerId: 'Officer ID / Email', password: 'Password', loginButton: 'Login', signup: 'Sign Up', autofillCredentials: 'Auto-fill demo credentials', demoCredentials: 'Prototype demonstration credentials', invalidLogin: 'Invalid Officer ID or password.', demoNote: 'This is a client-side prototype. No real account is created.', logout: 'Logout', dashboard: 'Officer Dashboard',
    home: 'Home', scanner: 'Scanner', team: 'Team', getStarted: 'Get Started', meetTeam: 'Meet the Team', scanProduct: 'Scan the Product', uploadImage: 'Upload Image', compliance: 'Compliance', compliant: 'COMPLIANT', nonCompliant: 'NON-COMPLIANT', violations: 'Violations', reports: 'Reports', evidence: 'Evidence', penaltyTracker: 'Penalty Tracker', repeatedOffenders: 'Repeated Offenders', sampleFixtures: 'Six Predefined Fixtures', aiAssistant: 'Officer Assistant', settings: 'Settings',
    overview: 'Compliance Overview', totalInspections: 'Total Inspections', compliantProducts: 'Compliant Products', nonCompliantProducts: 'Non-Compliant Products', violationsDetected: 'Violations Detected', reportsGenerated: 'Reports Generated', recentInspections: 'Recent Inspections', violationTracker: 'Statutory Violation Tracker (PCR 2011)', sampleData: 'Prototype fixture data', monitoring: 'Monitoring & Analytics', inspectionActivity: 'Inspection Activity', violationCategories: 'Violation Categories', noData: 'Fixture summaries only; no verified live evidence is connected.', prototypeAmount: 'Prototype amount',
    recentPackaging: 'Recent Packaging Inspections Audit', recentSub: 'Predefined product fixtures and their prepared findings', evidenceRef: 'Audit / Evidence Reference', location: 'Location', penaltyStatus: 'Penalty Status', currentStatus: 'Current Status', report: 'Report', downloadReport: 'Download Report', viewDetails: 'View Details',
    scannerTitle: 'Product Label Scanner', scannerSub: 'Select a packaged commodity label image from the library to verify legal declarations.', chooseLibrary: 'Choose from Library', noImage: 'No Label Image Selected', chooseToBegin: 'Choose a product label from the library to begin verification.', switchProduct: 'Switch Product', chooseAnother: 'Choose Another Image', analysis: 'Simulated Analysis Pipeline', ready: 'Ready to scan', generatingPdf: 'Generating Inspection PDF...', downloadPdf: 'Download Summary PDF', pdfDownloaded: 'Inspection report PDF downloaded', reportUnavailable: 'This inspection report is not available in the prototype dataset.',
    violationsFound: 'Violations Found', compliantElements: 'Compliant Elements', noViolations: 'No Statutory Violations Detected', value: 'Value', status: 'Status', severity: 'Severity', ruleReference: 'Rule Reference',
    assistantTitle: 'Officer Assistant (Legal Metrology AI)', assistantSub: 'Source-labeled prototype guidance for Mumbai enforcement workflows.', assistantDisclaimer: 'Prototype explanation only; not official legal advice.', assistantNoMatch: 'I could not find a source-backed answer for that question. Try asking about sources, rules, reports, or inspections.', sourceUnavailable: 'Verified source connection is not configured.', askQuestion: 'Ask a source-backed question', questionPlaceholder: 'Try: What sources does VeriLabel use?', ask: 'Ask', source: 'Source', close: 'Close', gotIt: 'Got it',
    homeHero: 'AI-Powered Packaging Label Verification', homeSub: 'Scan and verify packaged consumer products for legal metrology and label compliance easily.', demo: 'Product Demo Walkthrough', demoPlaying: 'Playing simulated optical scan flow...', demoIdle: 'Watch how VeriLabel highlights non-compliant declarations in seconds.', whatDoes: 'What VeriLabel Does', step1: '1. User Captures Image', step1d: 'User takes a photo of the product label.', step2: '2. AI Reads Label', step2d: 'AI analyzes the image and extracts key information.', step3: '3. Data Validation', step3d: 'The system checks extracted data against configured rules.', step4: '4. Report Generation', step4d: 'A comprehensive inspection PDF report is created.',
    backHome: 'Back to Home', tryScanner: 'Try the Product Scanner', cancel: 'Cancel', photos: 'Photos', selectLanguage: 'Select language', toggleTheme: 'Toggle theme', pagePrototype: 'VeriLabel prototype.'
  },
  hi: {
    brand: 'VeriLabel', motto: 'एवरी लेबल, वेरिफाइड।', prototype: 'प्रोटोटाइप', language: 'भाषा', theme: 'थीम', light: 'लाइट', dark: 'डार्क',
    roleTitle: 'आप अधिकारी हैं या ग्राहक?', roleSubtitle: 'VeriLabel का उपयोग करने का तरीका चुनें।', officer: 'अधिकारी', customer: 'ग्राहक', officerDesc: 'उत्पादों, अनुपालन, साक्ष्य और रिपोर्ट की समीक्षा करें।', customerDesc: 'निर्देशित प्रक्रिया में पैकेज्ड उत्पाद का लेबल सत्यापित करें।', continue: 'जारी रखें',
    login: 'अधिकारी लॉगिन', loginSub: 'प्रोटोटाइप प्रवर्तन कार्यक्षेत्र खोलें।', officerId: 'अधिकारी आईडी / ईमेल', password: 'पासवर्ड', loginButton: 'लॉगिन', signup: 'साइन अप', autofillCredentials: 'डेमो क्रेडेंशियल भरें', demoCredentials: 'प्रोटोटाइप प्रदर्शन क्रेडेंशियल', invalidLogin: 'अधिकारी आईडी या पासवर्ड गलत है।', demoNote: 'यह क्लाइंट-साइड प्रोटोटाइप है। कोई वास्तविक खाता नहीं बनाया जाता।', logout: 'लॉगआउट', dashboard: 'अधिकारी डैशबोर्ड',
    home: 'होम', scanner: 'स्कैनर', team: 'टीम', getStarted: 'शुरू करें', meetTeam: 'टीम से मिलें', scanProduct: 'उत्पाद स्कैन करें', uploadImage: 'छवि अपलोड करें', compliance: 'अनुपालन', compliant: 'अनुपालक', nonCompliant: 'अनुपालक नहीं', violations: 'उल्लंघन', reports: 'रिपोर्ट', evidence: 'साक्ष्य', penaltyTracker: 'दंड ट्रैकर', repeatedOffenders: 'बार-बार उल्लंघन', sampleFixtures: 'छह पूर्वनिर्धारित नमूने', aiAssistant: 'अधिकारी सहायक', settings: 'सेटिंग्स',
    overview: 'अनुपालन अवलोकन', totalInspections: 'कुल निरीक्षण', compliantProducts: 'अनुपालक उत्पाद', nonCompliantProducts: 'गैर-अनुपालक उत्पाद', violationsDetected: 'पता चले उल्लंघन', reportsGenerated: 'बनी रिपोर्ट', recentInspections: 'हाल के निरीक्षण', violationTracker: 'वैधानिक उल्लंघन ट्रैकर (PCR 2011)', sampleData: 'मुंबई क्षेत्र • प्रोटोटाइप नमूना डेटा', monitoring: 'निगरानी और विश्लेषण', inspectionActivity: 'निरीक्षण गतिविधि', violationCategories: 'उल्लंघन श्रेणियां', noData: 'सत्यापित लाइव डेटा जुड़ा नहीं है।', prototypeAmount: 'प्रोटोटाइप',
    recentPackaging: 'हालिया पैकेजिंग निरीक्षण ऑडिट', recentSub: 'क्षेत्रीय निरीक्षणों में वैधानिक सत्यापन फीड', evidenceRef: 'ऑडिट / साक्ष्य संदर्भ', location: 'स्थान', penaltyStatus: 'दंड स्थिति', currentStatus: 'वर्तमान स्थिति', report: 'रिपोर्ट', downloadReport: 'रिपोर्ट डाउनलोड करें', viewDetails: 'विवरण देखें',
    scannerTitle: 'उत्पाद लेबल स्कैनर', scannerSub: 'कानूनी घोषणाओं को सत्यापित करने के लिए लाइब्रेरी से पैकेज्ड उत्पाद की छवि चुनें।', chooseLibrary: 'लाइब्रेरी से चुनें', noImage: 'कोई लेबल छवि नहीं चुनी गई', chooseToBegin: 'सत्यापन शुरू करने के लिए लाइब्रेरी से उत्पाद लेबल चुनें।', switchProduct: 'उत्पाद बदलें', chooseAnother: 'दूसरी छवि चुनें', analysis: 'सिम्युलेटेड विश्लेषण पाइपलाइन', ready: 'स्कैन के लिए तैयार', generatingPdf: 'निरीक्षण PDF बनाई जा रही है...', downloadPdf: 'सारांश PDF डाउनलोड करें', pdfDownloaded: 'निरीक्षण रिपोर्ट PDF डाउनलोड हुई', reportUnavailable: 'यह निरीक्षण रिपोर्ट प्रोटोटाइप डेटा में उपलब्ध नहीं है।',
    violationsFound: 'मिले उल्लंघन', compliantElements: 'अनुपालक तत्व', noViolations: 'कोई वैधानिक उल्लंघन नहीं मिला', value: 'मान', status: 'स्थिति', severity: 'गंभीरता', ruleReference: 'नियम संदर्भ',
    assistantTitle: 'अधिकारी सहायक (Legal Metrology AI)', assistantSub: 'मुंबई प्रवर्तन कार्यप्रवाह के लिए स्रोत-चिह्नित प्रोटोटाइप मार्गदर्शन।', assistantDisclaimer: 'केवल प्रोटोटाइप व्याख्या; आधिकारिक कानूनी सलाह नहीं।', assistantNoMatch: 'इस प्रश्न के लिए कोई स्रोत-आधारित उत्तर नहीं मिला। स्रोत, नियम, रिपोर्ट या निरीक्षण के बारे में पूछें।', sourceUnavailable: 'सत्यापित स्रोत कनेक्शन कॉन्फ़िगर नहीं है।', askQuestion: 'स्रोत-आधारित प्रश्न पूछें', questionPlaceholder: 'पूछें: VeriLabel किन स्रोतों का उपयोग करता है?', ask: 'पूछें', source: 'स्रोत', close: 'बंद करें', gotIt: 'समझ गया',
    homeHero: 'AI-संचालित पैकेजिंग लेबल सत्यापन', homeSub: 'पैकेज्ड उपभोक्ता उत्पादों के कानूनी मेट्रोलॉजी और लेबल अनुपालन को आसानी से जांचें।', demo: 'उत्पाद डेमो वॉकथ्रू', demoPlaying: 'सिम्युलेटेड ऑप्टिकल स्कैन चल रहा है...', demoIdle: 'देखें कि VeriLabel गैर-अनुपालक घोषणाओं को कैसे दिखाता है।', whatDoes: 'VeriLabel क्या करता है', step1: '1. उपयोगकर्ता छवि लेता है', step1d: 'उपयोगकर्ता उत्पाद लेबल की तस्वीर लेता है।', step2: '2. AI लेबल पढ़ता है', step2d: 'AI छवि का विश्लेषण कर महत्वपूर्ण जानकारी निकालता है।', step3: '3. डेटा सत्यापन', step3d: 'सिस्टम निकाले गए डेटा को कॉन्फ़िगर नियमों से जांचता है।', step4: '4. रिपोर्ट बनाना', step4d: 'एक विस्तृत निरीक्षण PDF रिपोर्ट बनाई जाती है।',
    backHome: 'होम पर लौटें', tryScanner: 'उत्पाद स्कैनर आज़माएं', cancel: 'रद्द करें', photos: 'फ़ोटो', selectLanguage: 'भाषा चुनें', toggleTheme: 'थीम बदलें', pagePrototype: 'VeriLabel प्रोटोटाइप।'
  },
  mr: {
    brand: 'VeriLabel', motto: 'प्रत्येक लेबल, सत्यापित।', prototype: 'प्रोटोटाइप', language: 'भाषा', theme: 'थीम', light: 'लाइट', dark: 'डार्क',
    roleTitle: 'तुम्ही अधिकारी आहात की ग्राहक?', roleSubtitle: 'VeriLabel वापरण्याचा मार्ग निवडा.', officer: 'अधिकारी', customer: 'ग्राहक', officerDesc: 'उत्पादने, अनुपालन, पुरावे आणि अहवाल तपासा.', customerDesc: 'मार्गदर्शित प्रक्रियेत पॅकेज्ड उत्पादनाचा लेबल तपासा.', continue: 'पुढे जा',
    login: 'अधिकारी लॉगिन', loginSub: 'प्रोटोटाइप अंमलबजावणी कार्यक्षेत्र उघडा.', officerId: 'अधिकारी आयडी / ईमेल', password: 'पासवर्ड', loginButton: 'लॉगिन', signup: 'साइन अप', autofillCredentials: 'डेमो क्रेडेन्शियल आपोआप भरा', demoCredentials: 'प्रोटोटाइप प्रात्यक्षिक क्रेडेन्शियल', invalidLogin: 'अधिकारी आयडी किंवा पासवर्ड चुकीचा आहे.', demoNote: 'हे क्लायंट-साइड प्रोटोटाइप आहे. वास्तविक खाते तयार होत नाही.', logout: 'लॉगआउट', dashboard: 'अधिकारी डॅशबोर्ड',
    home: 'होम', scanner: 'स्कॅनर', team: 'टीम', getStarted: 'सुरू करा', meetTeam: 'टीमला भेटा', scanProduct: 'उत्पादन स्कॅन करा', uploadImage: 'प्रतिमा अपलोड करा', compliance: 'अनुपालन', compliant: 'अनुपालक', nonCompliant: 'अनुपालक नाही', violations: 'उल्लंघने', reports: 'अहवाल', evidence: 'पुरावा', penaltyTracker: 'दंड ट्रॅकर', repeatedOffenders: 'पुनरावृत्ती उल्लंघन', sampleFixtures: 'सहा पूर्वनिर्धारित नमुने', aiAssistant: 'अधिकारी सहाय्यक', settings: 'सेटिंग्ज',
    overview: 'अनुपालन आढावा', totalInspections: 'एकूण तपासणी', compliantProducts: 'अनुपालक उत्पादने', nonCompliantProducts: 'गैर-अनुपालक उत्पादने', violationsDetected: 'आढळलेली उल्लंघने', reportsGenerated: 'तयार अहवाल', recentInspections: 'अलीकडील तपासणी', violationTracker: 'वैधानिक उल्लंघन ट्रॅकर (PCR 2011)', sampleData: 'मुंबई क्षेत्र • प्रोटोटाइप नमुना डेटा', monitoring: 'निरीक्षण आणि विश्लेषण', inspectionActivity: 'तपासणी क्रिया', violationCategories: 'उल्लंघन श्रेणी', noData: 'सत्यापित लाइव्ह डेटा जोडलेला नाही.', prototypeAmount: 'प्रोटोटाइप',
    recentPackaging: 'अलीकडील पॅकेजिंग तपासणी ऑडिट', recentSub: 'क्षेत्रीय तपासण्यांमधील वैधानिक सत्यापन फीड', evidenceRef: 'ऑडिट / पुरावा संदर्भ', location: 'स्थान', penaltyStatus: 'दंड स्थिती', currentStatus: 'सध्याची स्थिती', report: 'अहवाल', downloadReport: 'अहवाल डाउनलोड करा', viewDetails: 'तपशील पहा',
    scannerTitle: 'उत्पादन लेबल स्कॅनर', scannerSub: 'कायदेशीर घोषणांची तपासणी करण्यासाठी लायब्ररीमधून पॅकेज्ड उत्पादनाची प्रतिमा निवडा.', chooseLibrary: 'लायब्ररीमधून निवडा', noImage: 'लेबल प्रतिमा निवडलेली नाही', chooseToBegin: 'तपासणी सुरू करण्यासाठी लायब्ररीमधून उत्पादन लेबल निवडा.', switchProduct: 'उत्पादन बदला', chooseAnother: 'दुसरी प्रतिमा निवडा', analysis: 'सिम्युलेटेड विश्लेषण पाइपलाइन', ready: 'स्कॅनसाठी तयार', generatingPdf: 'तपासणी PDF तयार होत आहे...', downloadPdf: 'सारांश PDF डाउनलोड करा', pdfDownloaded: 'तपासणी अहवाल PDF डाउनलोड झाला', reportUnavailable: 'हा तपासणी अहवाल प्रोटोटाइप डेटामध्ये उपलब्ध नाही.',
    violationsFound: 'आढळलेली उल्लंघने', compliantElements: 'अनुपालक घटक', noViolations: 'कोणतेही वैधानिक उल्लंघन आढळले नाही', value: 'मूल्य', status: 'स्थिती', severity: 'तीव्रता', ruleReference: 'नियम संदर्भ',
    assistantTitle: 'अधिकारी सहाय्यक (Legal Metrology AI)', assistantSub: 'मुंबई अंमलबजावणी कार्यप्रवाहासाठी स्रोत-चिन्हांकित प्रोटोटाइप मार्गदर्शन.', assistantDisclaimer: 'फक्त प्रोटोटाइप स्पष्टीकरण; अधिकृत कायदेशीर सल्ला नाही.', assistantNoMatch: 'या प्रश्नासाठी स्रोत-आधारित उत्तर सापडले नाही. स्रोत, नियम, अहवाल किंवा तपासणीबद्दल विचारा.', sourceUnavailable: 'सत्यापित स्रोत कनेक्शन कॉन्फिगर केलेले नाही.', askQuestion: 'स्रोत-आधारित प्रश्न विचारा', questionPlaceholder: 'विचारा: VeriLabel कोणते स्रोत वापरते?', ask: 'विचारा', source: 'स्रोत', close: 'बंद करा', gotIt: 'ठीक आहे',
    homeHero: 'AI-संचालित पॅकेजिंग लेबल सत्यापन', homeSub: 'पॅकेज्ड ग्राहक उत्पादनांचे कायदेशीर मेट्रोलॉजी आणि लेबल अनुपालन सहज तपासा.', demo: 'उत्पादन डेमो वॉकथ्रू', demoPlaying: 'सिम्युलेटेड ऑप्टिकल स्कॅन सुरू आहे...', demoIdle: 'VeriLabel गैर-अनुपालक घोषणा कसे दाखवते ते पहा.', whatDoes: 'VeriLabel काय करते', step1: '1. वापरकर्ता प्रतिमा घेतो', step1d: 'वापरकर्ता उत्पादन लेबलचा फोटो घेतो.', step2: '2. AI लेबल वाचते', step2d: 'AI प्रतिमेचे विश्लेषण करून महत्त्वाची माहिती काढते.', step3: '3. डेटा सत्यापन', step3d: 'सिस्टम काढलेल्या डेटाची कॉन्फिगर केलेल्या नियमांशी तपासणी करते.', step4: '4. अहवाल निर्मिती', step4d: 'सविस्तर तपासणी PDF अहवाल तयार केला जातो.',
    backHome: 'होमवर परत जा', tryScanner: 'उत्पादन स्कॅनर वापरा', cancel: 'रद्द करा', photos: 'फोटो', selectLanguage: 'भाषा निवडा', toggleTheme: 'थीम बदला', pagePrototype: 'VeriLabel प्रोटोटाइप.'
  }
} as const;

type TranslationKey = keyof typeof translations.en;
interface I18nValue { language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string; }
const I18nContext = createContext<I18nValue | undefined>(undefined);

export const I18nProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = window.localStorage.getItem('verilabel:language');
    return saved === 'hi' || saved === 'mr' ? saved : 'en';
  });
  const setLanguage = (next: Language) => { setLanguageState(next); window.localStorage.setItem('verilabel:language', next); };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
};

export const useI18n = () => { const value = useContext(I18nContext); if (!value) throw new Error('useI18n must be used inside I18nProvider'); return value; };
